### ISSUE TITLE
ReferenceError: window is not defined occurs in isomorphic app.

### ISSUE THREAD

**Issue by jeghers** [reactabular/reactabular#294]
We have tried using the reactabular table in our isomorphic app, and it worked ok for us, based on your endless scrolling example.  However, when our next step was to introduce the virtualization package (we need to have endless scroll over very large data), the app crashes in the browser and the following stacktrace is found in the server console:

`2017-04-21T05:02:44.951Z - error: ReferenceError: window is not defined
    at VirtualizedBody.render (/home/mark/grackle/grk-sd-prototype/node_modules/reactabular-virtualized/dist/body.js:153:52)
    at null.ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactCompositeComponent.js:815:34)
    at null.ReactCompositeComponentMixin._renderValidatedComponent (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactCompositeComponent.js:841:32)
    at null.ReactCompositeComponentMixin.performInitialMount (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactCompositeComponent.js:351:30)
    at null.ReactCompositeComponentMixin.mountComponent (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.ReactReconciler.mountComponent (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactMultiChild.js:215:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactDOMComponent.js:611:32)
    at ReactDOMComponent.Mixin.mountComponent (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactDOMComponent.js:493:29)
    at Object.ReactReconciler.mountComponent (/home/mark/grackle/grk-sd-prototype/node_modules/react/lib/ReactReconciler.js:46:35)`

**Comment by bebraw** [comment]
It's because there are lines like `process.env.NODE_ENV !== 'production' && window.LOG_VIRTUALIZED`. If you can figure out a way to rewrite those so that it works on SSR, I can merge a PR.

**Comment by bebraw** [comment]
If you use webpack, set `DefinePlugin` to rewrite `process.env.NODE_ENV` to `production`. You can achieve the same result through Babel. I discuss the topic in greater detail [here](https://survivejs.com/webpack/optimizing/environment-variables/).

**Comment by jrunge** [comment]
Any issues with checking if `window` is defined before performing the `window.LOG_VIRTUALIZED` check? i.e.

```
process.env.NODE_ENV !== 'production' && typeof window !== 'undefined' && window.LOG_VIRTUALIZED
```

It fixed the Server Side Rendering issue I was having in next.js and still allowed virtualized logging in the browser. I'll submit a PR.
